"""V14 fixed, newly authored mechanism tasks; not public benchmark data.

No earlier task templates, reference artifacts or model trajectories are used.
Only adapters/execution infrastructure are reused. Distinct authored structures
are clustering units, not a claim of IID population sampling or external validity.
Development obligations/probes are host-authored, NOT generated by Research.
"""

from __future__ import annotations

import itertools
from copy import deepcopy
from dataclasses import replace
from fractions import Fraction
from textwrap import dedent

from skillopt.coevolution_v3.executor import RepoTask
from skillopt.coevolution_v5.adapters import CodingAdapter
from skillopt.coevolution_v6.native import NativeAdapter
from skillopt.validator_pilot.api import digest

VERSION = "v14-new-constraint-probe-panel-v1"
SEED = 2026091504
ENTRY = "import logic\n\ndef solve(data):\n    return logic.run(data)\n"
CODING_DEV = ("integer-apportionment", "fixed-window-argmax", "ragged-column-layout", "signed-run-filter")
CODING_FINAL = ("strict-majority-vote", "balanced-binary-span", "next-greater-stack", "primitive-cycle-period",
                "unbounded-coin-change", "prefix-liquidity", "two-bin-feasibility", "frequency-policy-replacement")
SHEET_DEV = ("progressive-block-tariff", "affine-temperature-chain", "tank-volume-mass", "serial-yield-loss")
SHEET_FINAL = ("annular-coating", "compound-decay", "parallel-critical-path", "bilinear-interpolation",
               "resistor-topology", "fill-drain-duration", "signed-stock-variance", "equivalent-capital-time")
RULE_FINAL = ("two-of-three-quorum", "seeded-strong-component", "grounded-transitive-links", "conjunctive-ladder",
              "cross-product-certificates", "paired-output-fork", "new-policy-substitution", "threshold-cascade")


def _source(value):
    return dedent(value).strip() + "\n"


def _contract(scope="partial_update"):
    return {"change_scope": scope, "supersedes_old_policy": scope == "full_replacement",
            "preserve_obligations": ["Keep noneditable interfaces and explicitly retained audit outputs unchanged.",
                                     "Do not mutate input values; follow the declared runtime."]}


def _metadata(domain, family, split, smoke=False, scope="partial_update"):
    return {"version": VERSION, "domain": domain, "structural_family": family,
            "origin": "new_host_authored_synthetic_not_public_benchmark",
            "independence_unit": "authored_structure_not_case_or_repeat",
            "independence_is_design_assumption_not_population_guarantee": True,
            "historical_task_assets_used": False, "partition": split,
            "smoke_development_only": smoke, "contract": _contract(scope)}


def _obligations(statements):
    return [{"id": f"o{i}", "kind": kind, "statement": statement, "scope": "this_task_specification"}
            for i, (kind, statement) in enumerate(zip(("unit", "boundary", "order", "dependency"), statements))]


def _pairs(rows):
    return [{"values": list(values), "k": k} for values, k in rows]


# Reference bodies use a uniform two-file interface but genuinely different
# algorithms. Host oracles below use separately written enumeration/arithmetic.
_CODE = {
    CODING_DEV[0]: ("Distribute k indivisible seats in proportion to nonnegative integer weights. Take floor "
        "quotas, then give leftover seats by descending fractional remainder, ties by original index. "
        "If all weights are zero, allocate all zeros (unused seats are allowed only in this case).",
        '''
        values, k = data['values'], data['k']
        total = sum(values)
        if total == 0:
            result = [0 for x in values]
        else:
            result = [k*x//total for x in values]
            order = sorted(range(len(values)), key=lambda i: (-(k*values[i] % total), i))
            remaining = k-sum(result)
            for i in order[:remaining]:
                result[i] += 1
        ''',
        [("k*x//total", "(k*x+total-1)//total"), ("[0 for x in values]", "[k for x in values]"),
         ("% total), i)", "% total), -i)"), ("remaining = k-sum(result)", "remaining = 0")],
        [([2,3,5],7),([1,1,1],2),([],4),([0,0],3),([1,0,4],0),([3,7],9),([9],4),([5,2,5],5)],
        [([2,5,4],8),([0,0,0],7),([2,2,2],1),([3,4],5)],
        ["Quantize quotas to whole seats by flooring before distributing residual seats; never round quotas up.", "Zero total weight produces zero allocations.",
         "Equal fractional remainders use original index order.", "Residual allocation depends on the sum of floor quotas."]),
    CODING_DEV[1]: ("Find the contiguous window of exactly k values with greatest sum. Return [start,sum], "
        "using the earliest start on ties. For k=0 or k>length return [-1,0]. Values may be negative.",
        '''
        values, k = data['values'], data['k']
        result = [-1, 0]
        if 0 < k <= len(values):
            best = None
            for i in range(len(values)-k+1):
                candidate = sum(values[i:i+k])
                if best is None or candidate > best:
                    best = candidate
                    result = [i, candidate]
        ''',
        [("candidate = sum(values[i:i+k])", "candidate = sum(values[i:i+k])/k"),
         ("0 < k <= len(values)", "0 < k < len(values)"),
         ("candidate > best", "candidate >= best"),
         ("range(len(values)-k+1)", "range(len(values)-k)")],
        [([2,-1,4],2),([-3,-2,-5],1),([],0),([1,2],3),([2,2,2],2),([4,-4,9],3),([1,9],1),([0],0)],
        [([4,1,7],2),([3,8,1],3),([4,4,4,4],2),([-8,-2,9],1)],
        ["Window score is a sum, not an average.", "A window may equal the whole input length.",
         "Tied maxima retain the earliest start.", "The final valid starting position must be examined."]),
    CODING_DEV[2]: ("Interpret values as row-major rows of width k, pad only the final row with zeros, "
        "and return the column-major matrix: one list per column, row order retained. For k=0 or no values return [].",
        '''
        values, k = data['values'], data['k']
        result = []
        if k > 0 and values:
            rows = (len(values)+k-1)//k
            for col in range(k):
                column = []
                for row in range(rows):
                    index = row*k+col
                    column.append(values[index] if index < len(values) else 0)
                result.append(column)
        ''',
        [("else 0)", "else 1)"), ("(len(values)+k-1)//k", "len(values)//k"),
         ("range(k):", "range(k-1,-1,-1):"), ("index = row*k+col", "index = row+col")],
        [([1,2,3,4,5],3),([2,4],1),([],2),([3,4],0),([0],3),([1,2,3,4],2),([-1,-2,3],2),([7],1)],
        [([5,6,7],2),([8,2,3,5,9],4),([3,7,1,8],2),([4,7,9,2,5,8],3)],
        ["Padding represents missing entries and must be numeric zero.", "An incomplete final row is retained.",
         "Output columns preserve original left-to-right order.", "Source index equals row times width plus column."]),
    CODING_DEV[3]: ("Partition values into maximal consecutive equal-sign runs; zero has its own sign 0. "
        "Keep runs of length at least k and return [sign,length,signed_sum] for each retained run in input order. "
        "Negative sums must remain negative; do not merge separated runs of the same sign.",
        '''
        values, k = data['values'], data['k']
        groups = []
        for x in values:
            sign = 1 if x > 0 else -1 if x < 0 else 0
            if groups and groups[-1][0] == sign:
                groups[-1][1] += 1
                groups[-1][2] += x
            else:
                groups.append([sign, 1, x])
        result = [g for g in groups if g[1] >= k]
        ''',
        [("groups[-1][2] += x", "groups[-1][2] += abs(x)"),
         ("g[1] >= k", "g[1] > k"), ("result = [g for g in groups", "result = [g for g in reversed(groups)"),
         ("else -1 if x < 0 else 0", "else -1")],
        [([1,2,-1,-2,0,3],2),([0,0,-2,3],1),([],1),([-4,-3],2),([1,-1,1],1),([3,4],3),([0],0),([1,1,0,0,-2,-3],2)],
        [([-2,-5,-1],1),([4,5],2),([1,2,-3,-4],1),([0,-2,0],1)],
        ["Run sums retain signed numeric units.", "The threshold includes runs exactly k long.",
         "Retained runs remain in original sequence order.", "Zero is a distinct sign, not a negative value."]),
    CODING_FINAL[0]: ("Return the value occurring strictly more than half the time, or null when none exists. "
        "A value occurring exactly half is not a majority; k is unused.",
        '''
        values, k = data['values'], data['k']
        candidate, count = None, 0
        for x in values:
            if count == 0:
                candidate = x
            count += 1 if x == candidate else -1
        result = candidate if values and values.count(candidate)*2 > len(values) else None
        ''', [("*2 > len(values)", "*2 >= len(values)")],
        [([1,2,1],0),([2,3],0),([],0),([0],0),([1,2,3,2,2],0),([-1,-1,4],0),([1,1,2,2],0),([3,4,5],0)], [], []),
    CODING_FINAL[1]: ("For binary values, return the maximum length of a contiguous subarray containing "
        "equal numbers of zeros and ones. No such nonempty interval means zero; k is unused.",
        '''
        values, k = data['values'], data['k']
        first, balance, result = {0: -1}, 0, 0
        for i, x in enumerate(values):
            balance += 1 if x == 1 else -1
            if balance in first:
                result = max(result, i-first[balance])
            else:
                first[balance] = i
        ''', [("{0: -1}", "{0: 0}")],
        [([0,1],0),([1,1,0],0),([],0),([0,0],0),([1,0,1,0],0),([1],0),([0,1,1,1,0,0],0),([0,0,1,0,1],0)], [], []),
    CODING_FINAL[2]: ("For each position return the first later index with a STRICTLY greater value, or -1. "
        "Equal values do not satisfy the query; k is unused.",
        '''
        values, k = data['values'], data['k']
        result, stack = [-1]*len(values), []
        for i, x in enumerate(values):
            while stack and values[stack[-1]] < x:
                result[stack.pop()] = i
            stack.append(i)
        ''', [("values[stack[-1]] < x", "values[stack[-1]] <= x")],
        [([2,1,3],0),([2,2,3],0),([],0),([4],0),([5,4,3],0),([-2,-1,0],0),([1,3,2,4],0),([0,0,0],0)], [], []),
    CODING_FINAL[3]: ("Return the length of the shortest block whose repetitions exactly reproduce values. "
        "The block length must divide the sequence length; empty sequence has period zero; k is unused.",
        '''
        values, k = data['values'], data['k']
        result = len(values)
        for period in range(1,len(values)+1):
            if len(values)%period == 0 and all(x == values[i%period] for i,x in enumerate(values)):
                result = period
                break
        ''', [("len(values)%period == 0 and ", "")],
        [([1,2,1,2],0),([1,2,1],0),([],0),([3],0),([4,4,4],0),([1,2,3,1,2,3],0),([1,2,2,1],0),([0,1,0,1,0],0)], [], []),
    CODING_FINAL[4]: ("Coin denominations are positive integers. Return the fewest coins needed to total k "
        "with unlimited reuse, or -1 if impossible. Target zero needs zero coins; empty denominations are legal.",
        '''
        values, k = data['values'], data['k']
        dp = [0]+[k+1]*k
        for amount in range(1,k+1):
            for coin in values:
                if coin <= amount:
                    dp[amount] = min(dp[amount],dp[amount-coin]+1)
        result = dp[k] if dp[k] <= k else -1
        ''', [("coin <= amount", "coin < amount")],
        [([1,3,4],6),([2,5],5),([],3),([],0),([4,6],3),([3],9),([2,2,7],8),([5,1],0)], [], []),
    CODING_FINAL[5]: ("Values are signed cash flows in chronological order. Return [minimum_initial_cash, "
        "ending_cash] so the running balance never becomes negative. Preserve signed flows; do not floor "
        "individual negative flows or reorder them. k is unused.",
        '''
        values, k = data['values'], data['k']
        balance, low = 0, 0
        for x in values:
            balance += x
            low = min(low,balance)
        result = [-low, balance-low]
        ''', [("low = min(low,balance)", "low = min(0,balance)")],
        [([-4,7,-2],0),([2,-7,3],0),([],0),([3,5],0),([-1,-2,-3],0),([-5,5],0),([0,-2,4,-1],0),([9,-3,-9,8],0)], [], []),
    CODING_FINAL[6]: ("Assign every nonnegative item weight to one of TWO bins of capacity k. Return a "
        "boolean saying whether some partition is feasible; totals alone are insufficient. No splitting items.",
        '''
        values, k = data['values'], data['k']
        reachable = {0}
        for x in values:
            reachable = reachable | {s+x for s in reachable if s+x <= k}
        result = any(sum(values)-s <= k for s in reachable)
        ''', [("result = any(sum(values)-s <= k for s in reachable)", "result = sum(values) <= 2*k")],
        [([4,3,3],6),([4,4,4],6),([],0),([7],6),([2,2,2],3),([1,2,3],3),([0,0],0),([5,1,4,2],6)], [], []),
    CODING_FINAL[7]: ("NEW POLICY replaces original-occurrence order: return distinct values sorted by "
        "descending frequency, ties by ascending signed numeric value. Do NOT preserve previous encounter "
        "order. Other interface and input-preservation obligations still hold; k is unused.",
        '''
        values, k = data['values'], data['k']
        counts = {}
        for x in values:
            counts[x] = counts.get(x,0)+1
        result = sorted(counts,key=lambda x: (-counts[x],x))
        ''', [("(-counts[x],x)", "(-counts[x],values.index(x))")],
        [([3,1,3,1],0),([2,1,2],0),([],0),([-1,3,-1,3],0),([4,3,2,1],0),([0,0],0),([5,2,2,5,1],0),([-3,-2,-2],0)], [], []),
}


def _code_oracle(family, data):
    values, k = data["values"], data["k"]
    if family == CODING_DEV[0]:
        quotas = [Fraction(k*x, sum(values)) for x in values] if sum(values) else [Fraction(0) for _ in values]
        result = [int(q) for q in quotas]
        for i in sorted(range(len(values)), key=lambda i: (-(quotas[i]-int(quotas[i])), i))[:k-sum(result) if sum(values) else 0]:
            result[i] += 1
    elif family == CODING_DEV[1]:
        candidates = [(sum(values[i:i+k]), -i) for i in range(len(values)-k+1)] if 0 < k <= len(values) else []
        best = max(candidates) if candidates else (0, 1)
        result = [-best[1], best[0]]
    elif family == CODING_DEV[2]:
        rows = [values[i:i+k]+[0]*max(0, k-len(values[i:i+k])) for i in range(0, len(values), k)] if k else []
        result = [list(column) for column in zip(*rows)] if rows else []
    elif family == CODING_DEV[3]:
        result = []
        for sign, group in itertools.groupby(values, key=lambda x: (x > 0)-(x < 0)):
            items = list(group)
            if len(items) >= k:
                result.append([sign, len(items), sum(items)])
    elif family == CODING_FINAL[0]:
        result = next((x for x in set(values) if values.count(x) > len(values)/2), None)
    elif family == CODING_FINAL[1]:
        result = max([0]+[j-i for i in range(len(values)) for j in range(i+1,len(values)+1)
                          if values[i:j].count(0) == values[i:j].count(1)])
    elif family == CODING_FINAL[2]:
        result = [next((j for j in range(i+1,len(values)) if values[j] > x), -1) for i,x in enumerate(values)]
    elif family == CODING_FINAL[3]:
        result = next((i for i in range(1,len(values)+1) if values[:i]*(len(values)//i) == values), 0)
    elif family == CODING_FINAL[4]:
        frontier, result = {0}, 0 if k == 0 else -1
        for n in range(1,k+1):
            frontier = {x+coin for x in frontier for coin in values if x+coin <= k}
            if k in frontier:
                result = n
                break
    elif family == CODING_FINAL[5]:
        initial = max([0]+[-sum(values[:i]) for i in range(1,len(values)+1)])
        result = [initial, initial+sum(values)]
    elif family == CODING_FINAL[6]:
        result = any(sum(x for x,chosen in zip(values, mask) if chosen) <= k and
                     sum(x for x,chosen in zip(values, mask) if not chosen) <= k
                     for mask in itertools.product((False, True), repeat=len(values)))
    else:
        result = [x for _,x in sorted((-values.count(x),x) for x in set(values))]
    return {"result": result, "input_count": len(values), "input_sum": sum(values)}


def _coding(family, split="development", *, smoke=False):
    description, body, edits, regular, probes, statements = _CODE[family]
    source = "def run(data):\n" + "".join("    "+line+"\n" for line in _source(body).splitlines())
    source += "    return {'result':result,'input_count':len(values),'input_sum':sum(values)}\n"
    identifier = f"repo-v14-{'smoke-' if smoke else ''}{split}-{family}"
    scope = "full_replacement" if family == CODING_FINAL[7] else "partial_update"
    meta = _metadata("coding", family, split, smoke, scope)
    meta["obligations"] = _obligations(statements)
    cases = [{"label": f"{identifier}-case{i}", "input": data, "expected": _code_oracle(family,data),
              "exception": None, "public": i < 2, "dimension": "requested_behavior"}
             for i,data in enumerate(_pairs(regular))]
    mutants = []
    for before,after in edits:
        if source.count(before) != 1:
            raise ValueError("Ambiguous authored Coding mutation")
        mutants.append({"api.py": ENTRY, "logic.py": source.replace(before,after,1)})
    meta["counterexample_probe_pool"] = [
        {"id": f"{identifier}-probe{i}", "input": data, "expected": _code_oracle(family,data),
         "obligation_id": f"o{i}", "mutant": mutants[i]}
        for i,data in enumerate(_pairs(probes))]
    low = 0 if family in {CODING_DEV[0],CODING_FINAL[1],CODING_FINAL[4],CODING_FINAL[6]} else -50
    low = 1 if family == CODING_FINAL[4] else low
    domain = {"type":"object", "properties":{"values":{"type":"array","items":{"type":"integer","minimum":low,"maximum":100},"maxItems":12},
               "k":{"type":"integer","minimum":0,"maximum":100}}, "required":["values","k"],"additionalProperties":False}
    reference = {"api.py":ENTRY,"logic.py":source}
    starter = source
    for before, after in edits:
        starter = starter.replace(before, after, 1)
    meta["authored_starter_fault_count"] = len(edits)
    return CodingAdapter(RepoTask(id=identifier,split=split,family=family,cluster_id="v14-coding-"+family,
        prompt="Repair logic.py. "+description+" Return a dict with result, input_count, and input_sum. "
               "Audit fields are the ORIGINAL length and signed sum. Keep api.py unchanged and never mutate data.",
        files={"api.py":ENTRY,"logic.py":starter},reference_files=reference,editable_paths=["logic.py"],input_domain=domain,
        public_cases=cases[:2],private_cases=cases[2:],metadata=meta))


# (description, correct graph, independently checked fault per editable cell,
#  eight ordinary substitutions, four development-only challenge substitutions,
#  public obligation statements). Full oracle maps are never solver metadata.
_SHEET = {
    SHEET_DEV[0]: ("A1 usage units; A2 first-block limit; A3 first-block price per unit; A4 excess price "
        "per unit; A5 fixed charge; A6 audit multiplier. Quantities are nonnegative. B1 first-block usage, "
        "B2 excess usage, B3 first-block cost, B4 excess cost. C1 total including fixed charge; C2 usage reconciliation times A6.",
        {"B1":"=MIN(A1,A2)","B2":"=MAX(0,A1-A2)","B3":"=B1*A3","B4":"=B2*A4", "C1":"=B3+B4+A5","C2":"=(B1+B2)*A6"},
        [("B3","=B1+A3"),("B1","=A1"),("B4","=B2*A3"),("B2","=A1")],
        [(8,5,2,4,3,1),(3,5,2,4,1,2),(0,0,2,4,1,1),(5,5,2,3,0,2),(12,0,1,2,3,2),(9,3,0,4,2,3),(4,2,3,0,5,2),(10,6,2,5,2,1)],
        [(11,4,3,7,2,2),(13,3,2,5,1,1),(14,6,2,9,3,2),(15,7,3,4,2,3)],
        ["Multiplying usage by price produces cost units.","First-block usage cannot exceed its limit.",
         "The excess tier uses its own rate, not the first rate.","Excess usage excludes units already assigned to the first block."]),
    SHEET_DEV[1]: ("A1 Fahrenheit temperature (may be negative); A2 positive calibration scale; A3 signed "
        "calibration offset; A4 audit scale; A5/A6 signed audit offsets. B1 converts F to Celsius; B2 converts "
        "that Celsius to Kelvin. B3 applies calibration scale to Kelvin; B4 then adds calibration offset. "
        "C1 calibrated reading; C2=C1*A4+A5-A6. Do not clamp signed Celsius readings.",
        {"B1":"=(A1-32)*5/9","B2":"=B1+273.15","B3":"=B2*A2","B4":"=B3+A3","C1":"=B4","C2":"=C1*A4+A5-A6"},
        [("B1","=(A1-32)*9/5"),("B1","=MAX(0,(A1-32)*5/9)"),("B4","=(B2+A3)*A2"),("B2","=A1+273.15")],
        [(68,2,3,1,4,1),(14,1,-2,2,0,1),(32,1,0,1,0,0),(-40,2,5,1,1,2),(212,0.5,2,2,1,0),(50,3,-4,1,2,1),(0,1.5,7,2,3,1),(104,2,-1,3,2,1)],
        [(86,1,3,2,1,0),(-22,2,1,1,2,3),(77,3,5,2,1,1),(95,2,-3,1,0,2)],
        ["The F-to-C scale is five ninths after removing the Fahrenheit offset.","Signed Celsius temperatures must not be floored.",
         "Calibration offset is added after scaling, not scaled again.","Kelvin depends on converted Celsius, not directly on Fahrenheit."]),
    SHEET_DEV[2]: ("A1 supplied liters; A2 loss in milliliters; A3 tank capacity in liters; A4 density in "
        "grams per milliliter; A5 identical tank count; A6 overflow audit scale. All nonnegative. B1 surviving "
        "milliliters floored at zero; B2 stored milliliters limited by capacity; B3 grams per tank; B4 batch grams. "
        "C1 batch kilograms; C2 overflow milliliters times A6.",
        {"B1":"=MAX(0,A1*1000-A2)","B2":"=MIN(B1,A3*1000)","B3":"=B2*A4","B4":"=B3*A5","C1":"=B4/1000","C2":"=(B1-B2)*A6"},
        [("B1","=MAX(0,A1-A2)"),("B1","=A1*1000-A2"),("B2","=MIN(B1,A3)"),("B4","=B3+A5")],
        [(5,100,3,2,4,1),(2,500,3,1,2,2),(0,0,0,1,1,1),(1,2000,2,3,1,1),(3,0,0,1,2,3),(7,50,8,0,2,1),(4,500,2,2,0,1),(2.5,20,2,1.5,3,2)],
        [(6,25,4,2,3,1),(1,3000,3,2,4,1),(7,20,2,3,1,1),(8,40,3,2,5,1)],
        ["Convert liters to milliliters before subtracting milliliter loss.","Loss larger than supply leaves zero surviving volume.",
         "Capacity must be converted before applying the volume cap.","Batch mass scales the per-tank mass by tank count."]),
    SHEET_DEV[3]: ("A1 incoming mass; A2/A3 stage-one/stage-two yield fractions in [0,1]; A4 recovery "
        "fraction in [0,1]; A5 batch count; A6 audit scale. B1 stage-one retained mass; B2 stage-two retained "
        "mass; B3 first-stage waste; B4 second-stage waste. C1 usable mass includes final retained mass plus "
        "recovered waste from both stages. C2 reconciles retained plus both wastes times A5*A6.",
        {"B1":"=A1*A2","B2":"=B1*A3","B3":"=A1-B1","B4":"=B1-B2","C1":"=B2+(B3+B4)*A4","C2":"=(B2+B3+B4)*A5*A6"},
        [("B1","=A1+A2"),("B3","=0"),("B2","=A1*A3"),("B4","=A1-B2")],
        [(10,0.8,0.5,0.2,2,1),(12,0.5,0.5,0,1,2),(0,0,0,0,0,1),(8,0,1,1,2,1),(9,1,0,0.5,1,1),(6,1,1,0,3,2),(20,0.2,0.8,1,1,1),(7,0.6,0.4,0.3,2,3)],
        [(13,0.4,0.7,0.2,2,1),(11,0,0.5,0.8,1,2),(17,0.3,0.6,0.1,3,1),(19,0.5,0.2,0.4,1,1)],
        ["A yield is dimensionless and multiplies mass.","Zero first-stage yield puts all incoming mass into first-stage waste.",
         "Stage two operates on stage-one output, not initial input.","Second-stage waste subtracts output from that stage's own input."]),
    SHEET_FINAL[0]: ("A1 inner radius, A2 coating thickness (same length units), A3 cylinder height; A4 pi "
        "constant, A5 density, A6 piece count. All nonnegative. B1 outer radius; B2 annular area; B3 coating "
        "volume; B4 batch mass. C1=B4 and C2 volume plus annular area. Do not include the inner solid cylinder.",
        {"B1":"=A1+A2","B2":"=A4*(B1*B1-A1*A1)","B3":"=B2*A3","B4":"=B3*A5*A6","C1":"=B4","C2":"=B3+B2"},
        [("B1","=A2"),("B2","=A4*B1*B1"),("B3","=B2+A3")],[],[],[]),
    SHEET_FINAL[1]: ("A1 initial stock; A2/A3 successive loss fractions in [0,1]; A4 replenishment AFTER "
        "both losses; A5 unit value; A6 audit scale. B1 stock after first loss, B2 stock after second loss, "
        "B3 total lost stock, B4 final stock after replenishment. C1 final value; C2 lost plus retained-before-replenishment times A6.",
        {"B1":"=A1*(1-A2)","B2":"=B1*(1-A3)","B3":"=A1-B2","B4":"=B2+A4","C1":"=B4*A5","C2":"=(B3+B2)*A6"},
        [("B2","=A1*(1-A2-A3)"),("B3","=A1-B1"),("B4","=B2-A4")],[],[],[]),
    SHEET_FINAL[2]: ("A1 preparation duration; A2/A3 parallel branch durations; A4 join duration; A5 cost "
        "per unit of worker-time; A6 audit multiplier. B1 parallel elapsed duration; B2 total elapsed time; "
        "B3 total worker-time (both parallel branches count); B4 cost from worker-time. C1=B2; C2=B4*A6. All nonnegative.",
        {"B1":"=MAX(A2,A3)","B2":"=A1+B1+A4","B3":"=A1+A2+A3+A4","B4":"=B3*A5","C1":"=B2","C2":"=B4*A6"},
        [("B1","=A2+A3"),("B3","=B2"),("B4","=B2*A5")],[],[],[]),
    SHEET_FINAL[3]: ("A1/A2 are x/y fractions in [0,1]; A3 lower-left, A4 lower-right, A5 upper-left, "
        "A6 upper-right corner values (may be signed). B1 interpolates the lower edge in x; B2 interpolates "
        "the upper edge in x; B3 interpolates those two values in y; B4 is upper-minus-lower slope. C1=B3; C2=B1+B2.",
        {"B1":"=A3*(1-A1)+A4*A1","B2":"=A5*(1-A1)+A6*A1","B3":"=B1*(1-A2)+B2*A2","B4":"=B2-B1","C1":"=B3","C2":"=B1+B2"},
        [("B1","=A3*A1+A4*(1-A1)"),("B3","=(B1+B2)/2"),("B4","=MAX(0,B2-B1)")],[],[],[]),
    SHEET_FINAL[4]: ("A1/A2 positive resistances in parallel; A3 nonnegative series resistance; A4 voltage; "
        "A5 elapsed time; A6 audit scale. B1 parallel resistance; B2 total resistance; B3 current=voltage/total; "
        "B4 energy=current*voltage*time. C1=B4; C2=B1*A6. A4 may be signed; energy uses signed current times signed voltage.",
        {"B1":"=A1*A2/(A1+A2)","B2":"=B1+A3","B3":"=A4/B2","B4":"=B3*A4*A5","C1":"=B4","C2":"=B1*A6"},
        [("B1","=A1+A2"),("B3","=A4/B1"),("B4","=B3*A5")],[],[],[]),
    SHEET_FINAL[5]: ("A1 target volume; A2 current volume; A3 inflow; A4 outflow; A5 setup duration; A6 time "
        "audit multiplier. B1 additional volume=max(target-current,0); B2 signed net rate=inflow-outflow. "
        "B3 is zero when no volume is needed, -1 when volume is needed but net rate<=0, else B1/B2. "
        "B4 is -1 for impossible fill, else B3+A5. C1=B4; C2=B2*A6. Do not floor signed net rate or impossibility sentinel.",
        {"B1":"=MAX(0,A1-A2)","B2":"=A3-A4","B3":"=IF(B1==0,0,IF(B2<=0,-1,B1/B2))","B4":"=IF(B3<0,-1,B3+A5)","C1":"=B4","C2":"=B2*A6"},
        [("B2","=MAX(0,A3-A4)"),("B3","=IF(B2<=0,-1,B1/B2)"),("B4","=MAX(0,B3)+A5")],[],[],[]),
    SHEET_FINAL[6]: ("NEW POLICY replaces legacy nonnegative shortage reporting with SIGNED inventory "
        "variance. A1 opening inventory; A2 receipts; A3 shipments; A4 physical count; A5 signed unit adjustment "
        "value; A6 audit scale. B1 ledger closing quantity; B2 physical-minus-ledger variance; B3 signed adjustment "
        "value; B4 corrected ledger. C1=B3; C2=(B4-A4)*A6. Surplus and shortage must both retain their sign.",
        {"B1":"=A1+A2-A3","B2":"=A4-B1","B3":"=B2*A5","B4":"=B1+B2","C1":"=B3","C2":"=(B4-A4)*A6"},
        [("B2","=MAX(0,B1-A4)"),("B3","=MAX(0,B2)*A5"),("B4","=B1-B2")],[],[],[]),
    SHEET_FINAL[7]: ("A1/A2 principals invested for A3/A4 days respectively; A5 annual simple rate; A6 year "
        "length (>0). All nonnegative. B1/B2 capital-days; B3 sum capital-days; B4 earned simple interest "
        "(rate times capital-days divided by year length). C1=B4; C2 capital-days minus A1*A3-A2*A4. Do not compound interest.",
        {"B1":"=A1*A3","B2":"=A2*A4","B3":"=B1+B2","B4":"=B3*A5/A6","C1":"=B4","C2":"=B3-A1*A3-A2*A4"},
        [("B2","=A2*A3"),("B3","=(A1+A2)*(A3+A4)"),("B4","=B3*A5")],[],[],[]),
}


def _sheet_rows(family):
    if family in SHEET_DEV:
        return _SHEET[family][3]
    i = SHEET_FINAL.index(family)
    banks = [
        [(2,1,3,3.14,2,1),(0,2,4,3.14,1,3),(3,0,2,3,2,1),(1,1,0,3,1,1),(4,2,3,3,0,2),(2,3,1,3.14,2,0),(1,0.5,2,3,4,1),(5,1,2,3,1,4)],
        [(20,0.2,0.5,3,2,1),(8,0,1,2,3,2),(0,0,0,1,2,1),(15,1,0,4,2,3),(12,0.5,0.5,0,1,1),(10,0,0,5,0,1),(7,0.3,0.2,1,4,2),(18,0.8,0.1,2,1,3)],
        [(2,5,3,1,4,2),(0,1,7,2,3,1),(1,0,0,0,2,1),(2,3,3,4,1,1),(0,0,0,0,0,0),(5,1,2,3,0,2),(1,9,2,0,4,1),(3,2,8,5,2,4)],
        [(0.25,0.75,2,6,10,14),(0,1,-3,4,-5,8),(1,0,2,7,8,9),(0,0,-8,-2,5,3),(1,1,2,3,4,-7),(0.5,0.5,4,-4,-2,2),(0.1,0.9,0,10,20,-10),(0.8,0.2,-9,7,4,1)],
        [(2,3,4,12,5,1),(4,4,0,-8,3,2),(1,2,1,0,4,1),(8,2,3,9,0,2),(3,6,0,4,2,1),(5,5,5,-5,1,4),(2,7,1,3,2,3),(9,3,2,6,4,2)],
        [(10,2,5,1,3,2),(8,1,1,4,2,1),(0,0,0,0,1,1),(4,7,2,2,3,1),(7,2,3,3,0,2),(20,0,4,1,2,3),(5,5,0,4,0,1),(9,2,1,3,5,2)],
        [(10,3,2,9,4,1),(7,2,1,12,3,2),(0,0,0,0,2,1),(2,0,7,-3,2,1),(8,4,3,10,-2,1),(5,5,5,3,0,2),(4,1,2,3,2,3),(6,2,1,5,1,4)],
        [(100,50,30,60,0.1,360),(0,80,20,40,0.2,365),(0,0,0,0,0,360),(20,40,0,30,0.1,360),(50,0,90,0,0.2,365),(5,7,10,20,0,360),(80,40,15,25,0.08,365),(30,60,60,30,0.12,360)],
    ]
    return banks[i]


def _sheet_oracle(family, a):
    x,y,z,u,v,w = (a[f"A{i}"] for i in range(1,7))
    if family == SHEET_DEV[0]:
        low = x if x < y else y
        high = x-low
        b = [low, high, low*z, high*u]
        c = [low*z+high*u+v, x*w]
    elif family == SHEET_DEV[1]:
        cel = (x-32)/1.8
        kel = cel+273.15
        b = [cel,kel,kel*y,kel*y+z]
        c = [b[3],b[3]*u+v-w]
    elif family == SHEET_DEV[2]:
        volume = x*1000-y if x*1000 > y else 0
        stored = volume if volume < z*1000 else z*1000
        b = [volume,stored,stored*u,stored*u*v]
        c = [stored*u*v/1000,(volume-stored)*w]
    elif family == SHEET_DEV[3]:
        first_waste = x*(1-y)
        second_waste = x*y*(1-z)
        kept = x-first_waste-second_waste
        b = [x-first_waste,kept,first_waste,second_waste]
        c = [kept+(first_waste+second_waste)*u,x*v*w]
    elif family == SHEET_FINAL[0]:
        area = u*(2*x*y+y*y)
        b = [x+y,area,area*z,area*z*v*w]
        c = [b[3],area*(z+1)]
    elif family == SHEET_FINAL[1]:
        first_lost = x*y
        second_lost = (x-first_lost)*z
        b = [x-first_lost,x-first_lost-second_lost,first_lost+second_lost,x-first_lost-second_lost+u]
        c = [b[3]*v,x*w]
    elif family == SHEET_FINAL[2]:
        branch = y if y > z else z
        worker = x+y+z+u
        b = [branch,x+branch+u,worker,worker*v]
        c = [x+branch+u,worker*v*w]
    elif family == SHEET_FINAL[3]:
        lower, upper = z+(u-z)*x, v+(w-v)*x
        b = [lower,upper,lower+(upper-lower)*y,upper-lower]
        c = [b[2],lower+upper]
    elif family == SHEET_FINAL[4]:
        parallel = 1/(1/x+1/y)
        current = u/(parallel+z)
        b = [parallel,parallel+z,current,current*u*v]
        c = [b[3],parallel*w]
    elif family == SHEET_FINAL[5]:
        missing = x-y if x > y else 0
        rate = z-u
        duration = 0 if missing == 0 else -1 if rate <= 0 else missing/rate
        b = [missing,rate,duration,-1 if duration < 0 else duration+v]
        c = [b[3],rate*w]
    elif family == SHEET_FINAL[6]:
        ledger = x+y-z
        discrepancy = u-ledger
        b = [ledger,discrepancy,discrepancy*v,u]
        c = [discrepancy*v,0]
    else:
        capital_days = x*z+y*u
        b = [x*z,y*u,capital_days,(x*z/w+y*u/w)*v]
        c = [b[3],0]
    return {**{f"B{i+1}":value for i,value in enumerate(b)},"C1":c[0],"C2":c[1]}


def _sheet(family, split="development", *, smoke=False):
    description, formulas, defects, _, probes, statements = _SHEET[family]
    identifier = f"v14-sheet-{'smoke-' if smoke else ''}{split}-{family}"
    scope = "full_replacement" if family == SHEET_FINAL[6] else "partial_update"
    meta = _metadata("spreadsheet",family,split,smoke,scope)
    meta["obligations"] = _obligations(statements)
    editable = list(dict.fromkeys(cell for cell,_ in defects))
    reference = {"formulas":{cell:formulas[cell] for cell in editable}}
    regular = [{f"A{i+1}":value for i,value in enumerate(row)} for row in _sheet_rows(family)]
    cases = [{"id":f"{identifier}-case{i}","overrides":data,"expected":_sheet_oracle(family,data)}
             for i,data in enumerate(regular)]
    pool = []
    for i, row in enumerate(probes):
        data = {f"A{j+1}":value for j,value in enumerate(row)}
        mutant = deepcopy(reference)
        cell, bad = defects[i]
        mutant["formulas"][cell] = bad
        pool.append({"id":f"{identifier}-probe{i}","input":data,"expected":_sheet_oracle(family,data),
                     "obligation_id":f"o{i}","mutant":mutant})
    meta["counterexample_probe_pool"] = pool
    meta["authored_starter_fault_count"] = len(set(cell for cell,_ in defects))
    return NativeAdapter({"id":identifier,"domain":"spreadsheet","split":split,"family":family,
        "cluster_id":"v14-sheet-"+family,"contract":_contract(scope),"prompt":"Repair the editable formulas. "+description+
        " Check each intermediate output and both protected audits, not just C1; every legal input substitution must work.",
        "inputs":regular[0],"formulas":{**formulas,**dict(defects)},"editable_cells":editable,"answer_cell":"C1",
        "reference_artifact":reference,"public_cases":cases[:2],"hidden_cases":cases[2:],"metadata":meta})


_RULE = {
    RULE_FINAL[0]: ("a,b,c are three independent votes; q means any TWO votes are present. ready requires q "
        "and d (chair signoff). e is irrelevant. audit depends only on f. Do not count one vote twice.",
        [(["a","b"],"q"),(["a","c"],"q"),(["b","c"],"q"),(["q","d"],"ready")]),
    RULE_FINAL[1]: ("a seeds x; d independently seeds z. The propagation cycle is: x with b reaches y; "
        "y with c reaches z; z reaches x. ready needs y,z and e. A cycle without an external seed proves nothing. "
        "audit depends only on f.",
        [(["a"],"x"),(["d"],"z"),(["x","b"],"y"),(["y","c"],"z"),(["z"],"x"),(["y","z","e"],"ready")]),
    RULE_FINAL[2]: ("a certifies link A→B, b link B→C, c link C→D, d direct A→C, e direct B→D. "
        "Expose ab,bc,cd,ac,bd,ad when those directed links are directly certified or follow by transitivity. "
        "Do not reverse edges. audit depends only on f.",
        [(["a"],"ab"),(["b"],"bc"),(["c"],"cd"),(["d"],"ac"),(["e"],"bd"),
         (["ab","bc"],"ac"),(["bc","cd"],"bd"),(["ac","cd"],"ad"),(["ab","bd"],"ad")]),
    RULE_FINAL[3]: ("Four serial certification checkpoints are conjunctive: x requires a and b; y requires "
        "x and c; z requires y and d; ready requires z and e. Later checkpoints cannot substitute for earlier "
        "ones. audit depends only on f.",
        [(["a","b"],"x"),(["x","c"],"y"),(["y","d"],"z"),(["z","e"],"ready")]),
    RULE_FINAL[4]: ("A supplier certificate x may be obtained from a OR b; an independent transport "
        "certificate y from c OR d. ready requires BOTH certificate types and e. Two supplier certificates "
        "cannot replace transport. audit depends only on f.",
        [(["a"],"x"),(["b"],"x"),(["c"],"y"),(["d"],"y"),(["x","y","e"],"ready")]),
    RULE_FINAL[5]: ("One request a forks into two independently reportable outputs: x requires a and b; "
        "y requires a and c. z requires x and d; ready requires y and e. A failed right branch must not erase "
        "a successful left branch, or vice versa. audit depends only on f.",
        [(["a","b"],"x"),(["a","c"],"y"),(["x","d"],"z"),(["y","e"],"ready")]),
    RULE_FINAL[6]: ("NEW POLICY explicitly replaces legacy credential a: x now requires current credential "
        "b AND jurisdiction c, whether or not a exists. ready additionally requires d. e is unrelated legacy "
        "paperwork and must not be added as a condition. Preserve audit, which depends only on f.",
        [(["b","c"],"x"),(["x","d"],"ready")]),
    RULE_FINAL[7]: ("x requires both input attestations a,b. Independently, y requires any TWO of c,d,e. "
        "ready requires x AND y. Two attestations of the wrong type cannot substitute for each other. "
        "audit depends only on f.",
        [(["a","b"],"x"),(["c","d"],"y"),(["c","e"],"y"),(["d","e"],"y"),(["x","y"],"ready")]),
}


def _rule_oracle(family, facts):
    a,b,c,d,e,f = (name in facts for name in "abcdef")
    if family == RULE_FINAL[0]:
        q = sum((a,b,c)) >= 2
        observed = {"q":q,"ready":q and d}
    elif family == RULE_FINAL[1]:
        x, y, z = a or d, (a or d) and b, d or (a and b and c)
        observed = {"x":x,"y":y,"z":z,"ready":y and z and e}
    elif family == RULE_FINAL[2]:
        observed = {"ab":a,"bc":b,"cd":c,"ac":d or (a and b),"bd":e or (b and c),
                    "ad":(d and c) or (a and e) or (a and b and c)}
    elif family == RULE_FINAL[3]:
        observed = {"x":a and b,"y":a and b and c,"z":a and b and c and d,"ready":all((a,b,c,d,e))}
    elif family == RULE_FINAL[4]:
        observed = {"x":a or b,"y":c or d,"ready":(a or b) and (c or d) and e}
    elif family == RULE_FINAL[5]:
        observed = {"x":a and b,"y":a and c,"z":a and b and d,"ready":a and c and e}
    elif family == RULE_FINAL[6]:
        observed = {"x":b and c,"ready":b and c and d}
    else:
        observed = {"x":a and b,"y":sum((c,d,e)) >= 2,"ready":a and b and sum((c,d,e)) >= 2}
    return sorted(name for name,yes in {**observed,"audit":f}.items() if yes)


def _rule(family):
    description, declarations = _RULE[family]
    identifier = "v14-rule-final-"+family
    correct = [{"id":f"r{i}","if":antecedents,"then":consequence}
               for i,(antecedents,consequence) in enumerate(declarations)]
    correct.append({"id":"audit_rule","if":["f"],"then":"audit"})
    starter = deepcopy(correct)
    starter[0]["if"] = ["f"]
    scope = "full_replacement" if family == RULE_FINAL[6] else "partial_update"
    derived = sorted({r["then"] for r in correct})
    facts = [[letter for letter,present in zip("abcdef",bits) if present]
             for bits in itertools.product((False,True),repeat=6)]
    # Public cases show both a positive rich state and a sparse state; all other
    # truth assignments remain hidden. They are not extra independent tasks.
    facts = [facts[-1],facts[1],*facts[2:-1],facts[0]]
    cases = [{"id":f"{identifier}-case{i}","facts":row,"expected":_rule_oracle(family,row)}
             for i,row in enumerate(facts)]
    return NativeAdapter({"id":identifier,"domain":"rule_reasoning","split":"final","family":family,
        "cluster_id":"v14-rule-"+family,"contract":_contract(scope),"prompt":description+
        " Repair the existing editable rules; report every requested derived fact, not just ready.",
        "rules":starter,"editable_rule_ids":[r["id"] for r in correct[:-1]],"vocabulary":sorted(set("abcdef")|set(derived)),
        "initial_facts":facts[0],"answer_facts":derived,"public_cases":cases[:2],"hidden_cases":cases[2:],
        "reference_artifact":{"rules":correct},"metadata":_metadata("rule_reasoning",family,"final",False,scope)})


def payload(adapter):
    """Host-only; includes reference/probe definitions. Never solver projection."""
    return adapter.task.to_dict() if isinstance(adapter,CodingAdapter) else deepcopy(adapter.task)


def _development(adapter):
    row = payload(adapter)
    if row["split"] != "development" or row["metadata"].get("partition") != "development":
        raise ValueError("Only development tasks can expose obligations or probes")
    if row["metadata"].get("source_task_id"):
        raise ValueError("Probe tasks cannot recursively provide further probes")
    return row


def constraints_for(adapter):
    return deepcopy(_development(adapter)["metadata"]["obligations"])


def public_payload(adapter):
    from skillopt.coevolution_v8.feedback_study import public_task

    result = public_task(adapter)
    result["domain"] = adapter.domain
    row = payload(adapter)
    if adapter.domain == "coding":
        result["contract"] = deepcopy(row["metadata"]["contract"])
    if row["split"] == "development" and not row["metadata"].get("source_task_id"):
        result["obligations"] = constraints_for(adapter)
    return result


def probe_adapter(adapter):
    """Four separate challenge cases, never training/final fixtures or references."""
    row = _development(adapter)
    probes = row["metadata"]["counterexample_probe_pool"]
    if len(probes) != 4 or len({p["obligation_id"] for p in probes}) != 4:
        raise ValueError("Exactly four distinct authored obligation probes are required")
    identifier = row["id"]+"-dev-probe"
    meta = deepcopy(row["metadata"])
    meta.update(source_task_id=row["id"],source_task_hash=digest(row),counterexample_probe_pool=[],
                case_obligations={p["id"]:p["obligation_id"] for p in probes})
    if isinstance(adapter,CodingAdapter):
        cases = [{"label":p["id"],"input":deepcopy(p["input"]),"expected":deepcopy(p["expected"]),
                  "exception":None,"public":True,"dimension":"requested_behavior","obligation_id":p["obligation_id"]}
                 for p in probes]
        return CodingAdapter(replace(RepoTask.from_dict(row),id=identifier,public_cases=cases,private_cases=[],metadata=meta))
    row.update(id=identifier,metadata=meta,public_cases=[{"id":p["id"],"overrides":deepcopy(p["input"]),
        "expected":deepcopy(p["expected"]),"obligation_id":p["obligation_id"]} for p in probes],hidden_cases=[])
    return NativeAdapter(row)


def build_panel(smoke=False):
    if type(smoke) is not bool:
        raise ValueError("smoke must be a boolean")
    if smoke:
        train = [_coding(CODING_DEV[0],smoke=True),_sheet(SHEET_DEV[0],smoke=True)]
        final = [_coding(CODING_DEV[1],"final",smoke=True),_sheet(SHEET_DEV[1],"final",smoke=True)]
        for adapter in train+final:
            metadata = adapter.task.metadata if isinstance(adapter,CodingAdapter) else adapter.task["metadata"]
            metadata["origin"] = "development_structure_smoke_only_not_formal_heldout"
        return {"train":[train],"final":final}
    train = [[*[_coding(f) for f in CODING_DEV[2*r:2*r+2]],*[_sheet(f) for f in SHEET_DEV[2*r:2*r+2]]]
             for r in range(2)]
    return {"train":train,"final":[*[_coding(f,"final") for f in CODING_FINAL],
        *[_sheet(f,"final") for f in SHEET_FINAL],*[_rule(f) for f in RULE_FINAL]]}


def panel_manifest(panel):
    def item(adapter):
        row = payload(adapter)
        return {"task_id":row["id"],"domain":adapter.domain,"family":row["family"],"cluster_id":row["cluster_id"],
                "split":row["split"],"task_hash":digest(row),"public_hash":digest(public_payload(adapter))}
    return {"version":VERSION,"seed":SEED,"synthetic_not_public_benchmark":True,
            "host_authored_obligations_and_probes_not_deepresearch_generated":True,
            "train":[[item(a) for a in batch] for batch in panel["train"]],"final":[item(a) for a in panel["final"]]}


def artifact_controls(adapter):
    row = payload(adapter)
    if isinstance(adapter,CodingAdapter):
        reference = deepcopy(row["reference_files"])
        semantic = {**reference,"logic.py":"def run(data):\n    return {'incorrect_v14_control':0}\n"}
        source = reference["logic.py"].replace("def run(data):","def compute(data):",1)
        preservation = {**reference,"logic.py":source+"\ndef run(data):\n    result=compute(data)\n"
                        "    data['forbidden_v14_write']=1\n    return result\n"}
        return {"reference":reference,"starter":deepcopy(row["files"]),"semantic_mutant":semantic,
                "preservation_mutant":preservation}
    reference = deepcopy(row["reference_artifact"])
    semantic,preservation = deepcopy(reference),deepcopy(reference)
    if adapter.domain == "spreadsheet":
        starter = {"formulas":{k:row["formulas"][k] for k in row["editable_cells"]}}
        semantic["formulas"][row["editable_cells"][0]] = "=999991"
        preservation["formulas"]["C1"] = "=0"
    else:
        starter = {"rules":deepcopy(row["rules"])}
        semantic["rules"][0]["if"] = ["f"]
        preservation["rules"][-1]["if"] = ["a"]
    return {"reference":reference,"starter":starter,"semantic_mutant":semantic,"preservation_mutant":preservation}


def _control_evaluate(adapter, artifact):
    if isinstance(adapter,CodingAdapter):
        from skillopt.coevolution_v3 import executor

        native = executor.evaluate(adapter.task,{"files":{p:artifact[p] for p in adapter.task.editable_paths}})
        return {"passed":native.get("hard") is True,
                "available":native.get("execution_ok") is True and native.get("hard") is not None},native
    native = adapter.evaluate(artifact)
    return {"passed":native["score"] == 1,"available":native["score"] is not None},native


def self_check(panel, *, coding=True):
    """No model, no resampling. Reference code executes only in existing OS sandbox.

    Probe inputs are disjoint from ordinary cases; each isolated mutant must fail
    its specifically bound obligation probe, not merely some other test case.
    Only counts, identities, hashes and boolean calibration summaries are returned.
    """
    rows,probe_rows,seen = [],[],set()
    adapters = [a for batch in panel["train"] for a in batch]+panel["final"]
    for adapter in adapters:
        task = payload(adapter)
        if task["id"] in seen:
            raise ValueError("Duplicate task ID across partitions")
        seen.add(task["id"])
        if adapter.domain == "coding" and not coding:
            continue
        controls = {name:_control_evaluate(adapter,artifact)[0] for name,artifact in artifact_controls(adapter).items()}
        if (controls["reference"] != {"passed":True,"available":True} or
                any(controls[k]["passed"] for k in ("starter","semantic_mutant","preservation_mutant")) or
                any(not controls[k]["available"] for k in ("starter","semantic_mutant"))):
            raise ValueError("Reference/starter/mutant calibration failed: "+task["id"])
        rows.append({"task_id":task["id"],"domain":adapter.domain,"task_hash":digest(task),"controls":controls})
        if task["split"] != "development":
            continue
        probes = task["metadata"]["counterexample_probe_pool"]
        ordinary = task["public_cases"]+task["private_cases" if adapter.domain == "coding" else "hidden_cases"]
        field = "input" if adapter.domain == "coding" else "overrides"
        if {digest(c[field]) for c in ordinary}&{digest(p["input"]) for p in probes}:
            raise ValueError("Development probe inputs overlap ordinary fixtures")
        challenge = probe_adapter(adapter)
        correct,_ = _control_evaluate(challenge,artifact_controls(adapter)["reference"])
        if correct != {"passed":True,"available":True}:
            raise ValueError("Dedicated probe reference calibration failed: "+task["id"])
        checks = []
        for p in probes:
            status,native = _control_evaluate(challenge,p["mutant"])
            cases = native.get("case_results",[])
            prefix = p["id"]+":" if adapter.domain == "coding" else None
            specific = [c for c in cases if c["id"] == p["id"] or prefix and c["id"].startswith(prefix)]
            # Coding input-preservation must not be the only failure.
            relevant = [c for c in specific if adapter.domain != "coding" or c["id"].endswith(":behavior")]
            detected = bool(relevant) and any(c["passed"] is False for c in relevant)
            if not status["available"] or not detected:
                raise ValueError("Obligation mutant escaped its dedicated probe: "+task["id"]+"/"+p["obligation_id"])
            checks.append({"obligation_id":p["obligation_id"],"probe_id":p["id"],"detected":True,
                           "mutant_hash":digest(p["mutant"])})
        probe_rows.append({"task_id":task["id"],"probe_task_hash":digest(payload(challenge)),
                           "reference_passed":True,"ordinary_inputs_disjoint":True,"checks":checks})
    return {"version":VERSION+"-preflight","all_checked":True,"checked_tasks":len(rows),
            "coding_checked":bool(coding),"model_api_calls":0,"records":rows,"probe_records":probe_rows,
            "checked_probe_tasks":len(probe_rows),"checked_obligation_mutants":sum(len(r["checks"]) for r in probe_rows)}
