"""No live provider calls: immutable upstream receipts are generated by a fake."""
import json
from pathlib import Path

import pytest

from skillopt.skill_validation.stage2_transport import (
    MAX_OUTPUT_TOKENS,
    ProposalTransport,
    ProposalTransportError,
    fixture_development_views,
    main,
    run_fixture_proposals,
)
from skillopt.validator_pilot.api import digest, write_immutable_json


class FakeAPI:
    def __init__(self, root, *, attempts=1, ok=True, usage=None, responses=None, crash=None):
        self.root = Path(root)
        self.model, self.workers = "glm-5.3", 1
        self.service = {"max_retries": 2, "provider": "fixture-no-network"}
        self.attempts, self.ok = attempts, ok
        self.usage = {"prompt_tokens": 100, "completion_tokens": 20} if usage is None else usage
        self.responses = list(responses or [])
        self.crash = crash
        self.calls = []

    def call(self, system, user, kind, key, max_tokens=6000, repeat=0):
        request = {"model": self.model, "system": system, "user": user, "kind": kind, "key": key,
                   "max_tokens": max_tokens, "repeat": repeat, "service": self.service}
        identifier = digest(request)
        path = self.root / "calls" / (identifier + ".json")
        if path.exists():
            return json.loads(path.read_text())
        self.calls.append(request)
        if self.crash:
            raise self.crash("sensitive-marker-must-not-be-logged")
        response = self.responses.pop(0) if self.responses else {"status": "no_update", "questions": [], "urls": []}
        record = {"request_hash": identifier, "request": request, "ok": self.ok,
                  "response": json.dumps(response), "usage": self.usage,
                  "attempts": [{"attempt": i + 1, "ok": self.ok and i == self.attempts - 1,
                                "status": 200 if self.ok and i == self.attempts - 1 else 503,
                                "error_type": "fixture"} for i in range(self.attempts)],
                  "http_attempt_count": self.attempts}
        write_immutable_json(path, record)
        return record


def setup(tmp_path, **kwargs):
    api = FakeAPI(tmp_path / "api", **kwargs)
    return api, ProposalTransport(api, tmp_path / "transport")


def test_success_records_logical_http_usage_and_upstream_hash(tmp_path):
    api, transport = setup(tmp_path)
    reply = transport("system", "user", MAX_OUTPUT_TOKENS)
    assert reply.input_tokens == 100 and reply.output_tokens == 20 and not reply.cached
    report = transport.accounting()
    assert report["logical_requests_reserved"] == report["retained_upstream_http_attempts"] == 1
    assert report["new_http_attempts_this_invocation"] == 1
    assert report["all_attempt_token_usage_complete"] is True
    terminal = json.loads(next((tmp_path / "transport/terminal").glob("*.json")).read_text())
    assert terminal["upstream_record_hash"] and terminal["upstream_request_hash"]
    assert terminal["upstream_cache_ref"].startswith("calls/")
    assert len(api.calls) == 1


def test_three_http_attempts_not_misreported_as_one_call_cost(tmp_path):
    _, transport = setup(tmp_path, attempts=3)
    transport("system", "user", 200)
    report = transport.accounting()
    assert report["logical_requests_reserved"] == 1
    assert report["retained_upstream_http_attempts"] == report["new_http_attempts_this_invocation"] == 3
    assert report["all_attempt_token_usage_complete"] is False
    assert report["input_tokens_all_attempts"] is report["output_tokens_all_attempts"] is None
    assert report["terminal_attempt_usage"][0]["input_tokens"] == 100


def test_missing_usage_is_unknown_not_free(tmp_path):
    _, transport = setup(tmp_path, usage={})
    reply = transport("system", "user", 200)
    assert reply.input_tokens is reply.output_tokens is None
    report = transport.accounting()
    assert not report["all_attempt_token_usage_complete"] and report["input_tokens_all_attempts"] is None


def test_byte_identical_replay_uses_no_http_and_verifies_original_receipts(tmp_path):
    api, transport = setup(tmp_path)
    first = transport("system", "user", 200)
    snapshot = {str(p): p.read_bytes() for p in tmp_path.rglob("*.json")}
    resumed_api = FakeAPI(api.root, crash=RuntimeError)
    resumed = ProposalTransport(resumed_api, transport.root)
    second = resumed("system", "user", 200)
    assert second.cached and second.content == first.content and not resumed_api.calls
    assert resumed.accounting()["new_http_attempts_this_invocation"] == 0
    assert resumed.accounting()["retained_upstream_http_attempts"] == 1
    assert snapshot == {str(p): p.read_bytes() for p in tmp_path.rglob("*.json")}


def test_upstream_cache_modified_after_terminal_is_refused(tmp_path):
    api, transport = setup(tmp_path)
    transport("system", "user", 200)
    path = next((api.root / "calls").glob("*.json"))
    raw = json.loads(path.read_text())
    raw["response"] = "modified-after-terminal"
    path.write_text(json.dumps(raw))
    with pytest.raises(ValueError, match="receipt changed"):
        transport("system", "user", 200)


def test_terminal_failure_is_cached_not_silently_retried(tmp_path):
    api, transport = setup(tmp_path, attempts=3, ok=False)
    with pytest.raises(ProposalTransportError, match="upstream_terminal_failure"):
        transport("system", "user", 200)
    with pytest.raises(ProposalTransportError, match="upstream_terminal_failure"):
        transport("system", "user", 200)
    assert len(api.calls) == 1
    report = transport.accounting()
    assert report["terminal_status_counts"]["api_failure"] == 1 and report["retained_upstream_http_attempts"] == 3


def test_exception_is_persisted_as_category_without_sensitive_text(tmp_path):
    api, transport = setup(tmp_path, crash=RuntimeError)
    with pytest.raises(ProposalTransportError, match="api_call_or_receipt_validation_failed"):
        transport("system", "user", 200)
    text = "".join(p.read_text() for p in tmp_path.rglob("*.json"))
    assert "sensitive-marker" not in text
    assert transport.accounting()["retained_upstream_http_attempts"] is None
    with pytest.raises(ProposalTransportError):
        transport("system", "user", 200)
    assert len(api.calls) == 1


def test_process_interruption_keeps_intent_and_refuses_automatic_retry(tmp_path):
    api, transport = setup(tmp_path, crash=KeyboardInterrupt)
    with pytest.raises(KeyboardInterrupt):
        transport("system", "user", 200)
    resumed = ProposalTransport(FakeAPI(api.root), transport.root)
    with pytest.raises(ProposalTransportError, match="interrupted_transport_intent"):
        resumed("system", "user", 200)
    assert not resumed.api.calls
    assert resumed.accounting()["interrupted_without_terminal"] == 1
    assert resumed.accounting()["retained_upstream_http_attempts"] is None


def test_global_four_logical_call_cap_survives_restart(tmp_path):
    api, transport = setup(tmp_path)
    for number in range(4):
        transport("system", str(number), 200)
    resumed = ProposalTransport(api, transport.root)
    with pytest.raises(ValueError, match="Four-logical-call"):
        resumed("system", "fifth-call", 200)
    assert len(api.calls) == 4


@pytest.mark.parametrize("tokens", [True, 0, 2049, -1])
def test_output_cap_refuses_before_network(tmp_path, tokens):
    api, transport = setup(tmp_path)
    with pytest.raises(ValueError, match="2048-token cap"):
        transport("system", "user", tokens)
    assert not api.calls


@pytest.mark.parametrize("field,value", [("workers", 2), ("model", "other-model")])
def test_model_and_worker_configuration_fixed(tmp_path, field, value):
    api = FakeAPI(tmp_path / "api")
    setattr(api, field, value)
    with pytest.raises(ValueError):
        ProposalTransport(api, tmp_path / "transport")


def test_no_update_fixture_proposals_are_not_method_effect_evidence(tmp_path):
    api = FakeAPI(tmp_path / "api")
    def forbidden_fetch(*_):
        raise AssertionError("no_update must not retrieve")
    report = run_fixture_proposals(api, tmp_path / "run", fetcher=forbidden_fetch)
    assert report["proposal_statuses"] == {"adaptive_no_research": "no_update", "adaptive_research": "no_update"}
    assert len(api.calls) == 2 and report["source_kind"] == "fixture"
    assert report["candidate_executions"] == report["calibration_calls"] == 0
    assert report["formal_effect_estimate"] is report["deployment_authority"] is False
    resumed = run_fixture_proposals(api, tmp_path / "run", fetcher=forbidden_fetch)
    assert len(api.calls) == 2 and resumed["transport_accounting"]["new_http_attempts_this_invocation"] == 0
    first, second = (json.loads(call["user"]) for call in api.calls)
    assert first["development"] == second["development"]
    assert first["shared_project_context"] == second["shared_project_context"]


def test_development_fixture_views_have_no_execution_or_audit_answers():
    views = fixture_development_views()
    assert len(views) == 2
    for view in views:
        assert view["public_execution"] == []
        assert view["purpose"] == "proposal_development_not_blind_evaluation"
        assert all(g["category"] == "hypothesis" and not g["research_independent_discovery"] for g in view["development_gaps"])
    raw = json.dumps(views)
    for field in ("audit_status", "condition", "skill_hash", "reference_implementation"):
        assert field not in raw


def test_cli_setup_error_never_echoes_credentials(tmp_path, monkeypatch, capsys):
    def bad_api(*args, **kwargs):
        raise RuntimeError("sensitive-marker-key-or-header")
    monkeypatch.setattr("skillopt.skill_validation.stage2_transport.CachedAPI", bad_api)
    assert main(["--output", str(tmp_path / "out"), "--repo", str(tmp_path)]) == 2
    assert "sensitive-marker" not in capsys.readouterr().out
